### ISSUE TITLE
Windows/Linux support

### ISSUE THREAD

**Issue by mauri870** [mburakerman/mackernews#2]
Hi,

I've been testing the project locally on windows and it works as expected, I only found a single issue related to the icons.

If you are ok with supporting windows/ linux as well, we need to change the icon to be a .ico file as per getlantern instructions:

```txt
package systray // import "github.com/getlantern/systray"

func SetIcon(iconBytes []byte)
    SetIcon sets the systray icon. iconBytes should be the content of .ico for
    windows and .ico/.jpg/.png for other platforms.
```

Seems like a .ico is a good alternative that works for all platforms

Other than that everything just works out of the box.

**Comment by mburakerman** [comment]
heyyy!

i am currently only targeting mac, so the app is named accordingly.

but thanks for your interest!
